export const categories = [
  "Personal",
  "Learning",
  "Project",
  "Bug",
  "Issue",
  "Improvement",
  "Task",
  "Achievement",
];

export const tagsData = {
  Frontend: [
    "React",
    "Vue",
    "Angular",
    "HTML5",
    "CSS",
    "JavaScript",
    "Tailwind",
    "GSAP",
    "Svelte",
    "Bootstrap",
    "Material-UI",
    "Next.js",
    "jQuery",
    "Chakra UI",
  ],
  Backend: [
    "Node.js",
    "Express",
    "Django",
    "SpringBoot",
    "FastAPI",
    "Flask",
    "Ruby on Rails",
    "Laravel",
    "ASP.NET Core",
    "Hapi.js",
  ],
  Database: [
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "Redis",
    "SQLite",
    "Firebase",
    "Cassandra",
    "Elasticsearch",
    "Oracle",
  ],
  DevOps: [
    "Docker",
    "Kubernetes",
    "AWS",
    "CICD",
    "Git",
    "Ansible",
    "Terraform",
    "Jenkins",
    "Azure DevOps",
    "GCP",
    "GitHub Actions",
  ],
  AI: [
    "LangChain",
    "OpenAI",
    "Hugging Face",
    "Transformers",
    "ONNX",
    "Vision AI",
  ],
  ML: [
    "Data Preprocessing",
    "Model Training",
    "Model Evaluation",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Pandas",
    "XGBoost",
    "Keras",
    "Feature Engineering",
    "Model Deployment",
    "Hyperparameter Tuning",
    "Data Visualization",
  ],
  Personal: [
    "Diary",
    "Travel",
    "Goals",
    "Learning",
    "Productivity",
    "Health",
    "Mindfulness",
    "Projects",
    "Books",
    "Networking",
    "Self-Review",
  ],
};
